### ISSUE TITLE
Could this be run without docker?

### ISSUE THREAD

**Issue by Yankees4life** [drkno/transcoderr#38]
I'm wondering if this could be run without docker to take advantage of my Intel GPU.

**Comment by drkno** [comment]
Yes, it can. Just manually run the relevant commands from the Dockerfile: https://github.com/drkno/transcoderr/blob/master/Dockerfile

Note you can use your Intel GPU within docker by passing the `/dev/dri` device into the container: e.g. https://github.com/drkno/media-scripts/blob/main/docker-compose.yml#L240
